baseURL = "https://www.kulturbanausen-duesseldorf.de/"
languageCode = "en"
theme = "ghazal"

[outputs]
  home = ["HTML"]
  page = ["HTML"]

[params]
    title = "Kulturbanausen im Ratinger Hof"
    author = "Sia"
    description = "Ziel der Kulturbanausen ist es eine Kulturst채tte in der D체sseldorfer Altstadt zu etablieren, betreiben und zu erhalten."
    footer = "2020 Kulturbanausen eG iG."
    shortAbout = "Ziel der Kulturbanausen ist es eine Kulturst채tte in der D체sseldorfer Altstadt zu etablieren, betreiben und zu erhalten."
    mainimage = "images/logo.png"
    profileImage = "https://i.stack.imgur.com/oI2SB.jpg?s=328&g=1"

    [params.theme]
        fontSize = "16px"
        dateFormat = "2006/01/02"
        paginateNum = 5

    [params.social]
        twitter = "https://twitter.com/KBanausen"
        email= "mailto:info@kulturbanausen-duesseldorf.de?subject=Kontakt"
        instagram = "https://www.instagram.com/kulturbanausennrw/"
        facebook = "https://www.facebook.com/KulturbanausenNRW"
