baseURL = "https://www.kulturbanausen-duesseldorf.de/"
languageCode = "en"
theme = "ghazal"

[outputs]
  home = ["HTML"]
  page = ["HTML"]

[params]
    title = "Kulturbanausen im Ratinger Hof"
    author = "Sia"
    description = "Die Kulturbanausen e.G. i.G. ist eine Unternehmung mit dem Ziel ein soziokulturelles Zentrum in der Düsseldorfer Altstadt zu etablieren und zu erhalten, um die Subkulturen Düsseldorfs enger zusammen zu führen. Die Genossenschaft ist der Meinung, dass im Mittelpunkt eines geschichtlich wichtigen Knotenpunktes der Stadt, im Ratinger Hof, eine kulturelle Begegnungsstätte den idealen Platz finden würde. U.a. sind Konzerte, Poetry Slams, Theater, Work Shops, DJ Contests, Partys und viele weitere Projekte geplant. Die Kulturbanausen freuen sich auf das spannende Projekt mit Euch...! :-)"
    footer = "2020 Kulturbanausen eG iG."
    shortAbout = "Ziel der Kulturbanausen ist es eine Kulturstätte in der Düsseldorfer Altstadt zu etablieren, betreiben und zu erhalten."
    mainimage = "images/logo.png"
    profileImage = "https://i.stack.imgur.com/oI2SB.jpg?s=328&g=1"

    [params.theme]
        fontSize = "16px"
        dateFormat = "2006/01/02"
        paginateNum = 5

    [params.social]
        twitter = "https://twitter.com/KBanausen"
        email= "mailto:info@kulturbanausen-duesseldorf.de?subject=Kontakt"
        instagram = "https://www.instagram.com/kulturbanausennrw/"
        facebook = "https://www.facebook.com/KulturbanausenNRW"
